global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prom'
      username: 'linhptk'

remote_write:
  - url: "http://27.66.108.93:9090/api/v1/write"

  scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: [
      'localhost:9090',
      'localhost:9091'
    ]


  - job_name: 'node-exporter'
    static_configs:
    - targets: [
      'localhost:9100',
      'demo.do.prometheus.io:9100'
    ]

  - job_name: 'cadvisor'
    static_configs:
    - targets: [
      'localhost:8080',
    ]