- name: Pull MongoDB image from Docker Hub
  community.docker.docker_image:
    name: "{{ IMAGE_NAME }}"
    source: pull

- name: Create Database network
  community.docker.docker_network:
    name: "{{ NETWORK_NAME }}"

- name: Run docker image mongo
  community.docker.docker_container:
    name: mongo
    image: "{{ IMAGE_NAME }}"
    restart_policy: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - name: "{{ NETWORK_NAME }}"
      - name: "{{ FLUENT_NETWORK_NAME }}"
    volumes:
      - "{{ MONGODB_VOLUME }}"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ MONGO_ROOT_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ MONGO_ROOT_PASSWORD }}"
      MONGO_INITDB_DATABASE: "{{ DATABASE_NAME }}"
    log_driver: fluentd
    log_options:
      fluentd-address: "100.115.93.99:24224"
      tag: "docker.db"
  become: yes
