- name: Build frontend image
  community.docker.docker_image:
    name: "{{ IMAGE_NAME }}"
    build:
      path: ./app/frontend
    source: build

- name: Run frontend container
  community.docker.docker_container:
    name: frontend
    image: "{{ IMAGE_NAME }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ NETWORK_NAME }}"
      - name: "{{ FLUENT_NETWORK_NAME }}"
    ports:
      - "3030:3030"
    log_driver: fluentd
    log_options:
      fluentd-address: "100.115.93.99:24224"
      tag: "docker.web"
  tags: docker
